apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-go-server
  namespace: api-middleware
  labels:
    app: examplegoapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: examplegoapi
  template:
    metadata:
      labels:
        app: examplegoapi
    spec:
      imagePullSecrets:
      - name: pipeline-example-go-registry
      containers:
      - name: examplegoapi
        image: diegoedu11/example-pipeline-go:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: example-go-service
  #namespace: go
spec:
  selector:
    app: examplegoapi
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
